### ISSUE TITLE
Bejelentés a NAV felé improve

### ISSUE THREAD

**Issue by pihentagy** [hyperknot/interactive_brokers_tbsz#1]
https://github.com/hyperknot/interactive_brokers_tbsz/blob/16a18230d37bb0337e5ccee132bce0a93a671b9e/9.%20NAV%20bejelent%C3%A9s.md?plain=1#L1

Képes segítség (ügytípus, kötelező előzménysorszám): https://revb.hu/lightyear-tbsz-nav-bejelentes/

**Comment by hyperknot** [comment]
Köszi, átnéztem az egészet és megírtam ezt a részt is. A linkelt guide-ot beletettem.

**Comment by pihentagy** [comment]
Ja, nem saját iromány.

**Comment by hyperknot** [comment]
Végül inkább beleírtam a legfontosabb részeket meg kicseréltem a szöveget arra amit a PH fórumon ajánlottak, így most már nincs rá szükség.
