### ISSUE TITLE
404-es hiba 

### ISSUE THREAD

**Issue by wisewizard** [hyperknot/interactive_brokers_tbsz#3]
Oldal: [11. NAV bejelentés](https://github.com/hyperknot/interactive_brokers_tbsz/blob/main/ibkr/nav_bejelentes.md)

Hibás link és a helye: "Ennek a sablonnak van egy kitölthető változata, itt elérhető: [IB_TBSZ_agreement_editable.pdf](https://github.com/hyperknot/interactive_brokers_tbsz/blob/main/ibkr/sablonok/IB_TBSZ_agreement_editable.pdf) (köszönjük RoBos-nak a PH-ról hogy kitölthetővé tette)."

Helyes link: https://github.com/hyperknot/interactive_brokers_tbsz/blob/main/sablonok/IB_TBSZ_agreement_editable.pdf

Korábban volt egy ibkr mappa a sablonokon belül, ami megszűnt.

**Comment by hyperknot** [comment]
Köszönöm, javítottam őket (találtam még 2-t).
