### ISSUE TITLE
Erste számla megszüntetése a fiókban

### ISSUE THREAD

**Issue by zsmb13** [hyperknot/interactive_brokers_tbsz#5]
Ma reggel tartottam ennél a lépésnél:
https://github.com/hyperknot/interactive_brokers_tbsz/blob/main/erste/erste_fiok.md

Az ügyintéző mindenképpen ragaszkodott hozzá, hogy a megszüntetést nem tudjuk a transzferrel együtt lepapírozni, és vissza kell mennem még a transzfer után külön megszüntetni a számlát: "a felmondást központilag csinálják, csak a transzfer után lehet".

Később ha sikerült a transzfer és a megszüntetés visszajövök frissíteni ezt az issue-t / a fenti lépés szövegét.

**Comment by hyperknot** [comment]
Köszi, meg a PR-t is!

**Comment by zsmb13** [comment]
Végül inkább csak leírom a saját aktuális tapasztalatokat, nem tudom hogy lenne a legjobb beépíteni a meglévő leírásba, de nálam így nézett ki a fiókos ügyintézéstől a dolog:

**Okt 3:** fiókban transzfer elindítása
    (pár órával később telefonon értesülés hogy nincs elég pénz a számlán a transzfer fedezéséhez (https://github.com/hyperknot/interactive_brokers_tbsz/pull/4), utaltam még rá)

**Okt 10:** IBKR értesítés a bejövő transferről

**Okt 12:** IBKR figyelemztetés arról hogy bizonyos papírokhoz nincs real-time market data előfizetve, illetve nem a base currency-ben vannak jegyezve (ami ha jól értem TBSZ-nél a forint), ebben az emailben már látszik hogy milyen papírok fognak átmenni hozzájuk mert listázzák őket

**Okt 14:** megjelentek IBKR-en a papírok (az Ersténél is látszanak még eközben), kitöltöttem a cost basis adatokat, megjött a funding notice ami felszólít a NAV bejelentésre

**Okt 15:** átfutottak a cost basis változtatások, most már ahhoz képest látszanak a hozamok

**Okt 17:** visszamentem az Erste fiókba ismét időpontra, kérni a sima értékpapír számla megszüntetését, kifizették a maradék forintot készpénzben (ennek volt egy minimális díja, érdemes lehet előre kiutalni Netbrokerről ha tudja az ember hogy hogy kell), kb. 10 perc volt az ügyintézés

**Comment by hyperknot** [comment]
Köszi, belinkelem a leírásba ezt az issue-t.
